services:
  
  postgres:
    container_name: "iism_postgres"
    image: postgres:latest
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=iism
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-dump:/var/lib/postgresql/dump
    networks:
      - default
  
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=iism;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
    name: infra