//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Supplier {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Supplier() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Domain.Supplier", typeof(Supplier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        public static string SupplierPhoneNumber {
            get {
                return ResourceManager.GetString("SupplierPhoneNumber", resourceCulture);
            }
        }
        
        public static string SupplierEmail {
            get {
                return ResourceManager.GetString("SupplierEmail", resourceCulture);
            }
        }
        
        public static string SupplierAddress {
            get {
                return ResourceManager.GetString("SupplierAddress", resourceCulture);
            }
        }
        
        public static string SupplierStreet {
            get {
                return ResourceManager.GetString("SupplierStreet", resourceCulture);
            }
        }
        
        public static string SupplierCity {
            get {
                return ResourceManager.GetString("SupplierCity", resourceCulture);
            }
        }
        
        public static string SupplierState {
            get {
                return ResourceManager.GetString("SupplierState", resourceCulture);
            }
        }
        
        public static string SupplierCountry {
            get {
                return ResourceManager.GetString("SupplierCountry", resourceCulture);
            }
        }
        
        public static string SupplierPostalCode {
            get {
                return ResourceManager.GetString("SupplierPostalCode", resourceCulture);
            }
        }
    }
}
