//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Warehouse {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Warehouse() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Domain.Warehouse", typeof(Warehouse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WarehouseCapacity {
            get {
                return ResourceManager.GetString("WarehouseCapacity", resourceCulture);
            }
        }
        
        public static string WarehouseEmail {
            get {
                return ResourceManager.GetString("WarehouseEmail", resourceCulture);
            }
        }
        
        public static string WarehouseAddress {
            get {
                return ResourceManager.GetString("WarehouseAddress", resourceCulture);
            }
        }
        
        public static string WarehouseStreet {
            get {
                return ResourceManager.GetString("WarehouseStreet", resourceCulture);
            }
        }
        
        public static string WarehouseCity {
            get {
                return ResourceManager.GetString("WarehouseCity", resourceCulture);
            }
        }
        
        public static string WarehouseState {
            get {
                return ResourceManager.GetString("WarehouseState", resourceCulture);
            }
        }
        
        public static string WarehouseCountry {
            get {
                return ResourceManager.GetString("WarehouseCountry", resourceCulture);
            }
        }
        
        public static string WarehousePostalCode {
            get {
                return ResourceManager.GetString("WarehousePostalCode", resourceCulture);
            }
        }
    }
}
